/**
 * Stub file for api-routes to resolve Windows compilation issues
 */

interface ApiRoute {
  path: string;
  method: string;
  handler: (...args: unknown[]) => Promise<void>;
  description: string;
  inputSchema: object;
  outputSchema: object;
}

export const autoGeneratedApiRoutes: ApiRoute[] = [];
export function getApiRoutePaths(): string[] {
  return [];
}