/** Stub file for mcp-tools to resolve Windows compilation issues */

interface McpTool {
  name: string;
  description: string;
  inputSchema: object;
}

export const autoGeneratedMcpTools: McpTool[] = [];
export function getMcpToolNames(): string[] {
  return [];
}
