version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ExaDev"
    assignees:
      - "ExaDev"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    groups:
      # Group patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group minor TypeScript ecosystem updates
      typescript-ecosystem:
        patterns:
          - "typescript*"
          - "@typescript-eslint/*"
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      # Group testing dependencies
      testing-dependencies:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "eslint*"
          - "prettier*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "ExaDev"
    assignees:
      - "ExaDev"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all GitHub Actions updates together
      github-actions:
        patterns:
          - "*"