/**
 * MCP tool definitions derived from Zod schemas
 *
 * Replaces the generated mcp-tools.ts. Tool definitions are built at runtime
 * from Zod schemas using z.toJSONSchema(), ensuring they stay in sync with
 * the schema definitions automatically.
 */

import * as z from 'zod';
import type { Tool } from '@modelcontextprotocol/sdk/types.js';
import { methodSchemas } from './index.js';

/** Convert camelCase to snake_case for MCP tool naming */
function camelToSnake(str: string): string {
  return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
}

/** Derive the MCP tool description from the schema's JSON Schema output */
function getDescription(schema: z.ZodType): string {
  const jsonSchema = z.toJSONSchema(schema, { unrepresentable: 'any' });
  const desc = jsonSchema.description;
  return typeof desc === 'string' ? desc : '';
}

/** Build MCP tool definitions from Zod schemas at runtime */
function buildMcpTools(): Tool[] {
  const tools: Tool[] = [];

  for (const [methodName, schemas] of Object.entries(methodSchemas)) {
    const toolName = camelToSnake(methodName);
    const inputSchema = z.toJSONSchema(schemas.input, {
      target: 'draft-07',
      unrepresentable: 'any',
    });

    tools.push({
      name: toolName,
      description: getDescription(schemas.input),
      // z.toJSONSchema returns z.JSONSchema (a broad union type); MCP's Tool.inputSchema
      // is a narrower Zod-inferred shape. They are structurally compatible for object schemas
      // but TypeScript cannot verify this across the type boundary.
      inputSchema: inputSchema as Tool['inputSchema'],
    });
  }

  return tools;
}

/** Auto-generated MCP tools from Zod schemas */
export const autoGeneratedMcpTools: Tool[] = buildMcpTools();

/** Get MCP tool by name */
export function getMcpToolByName(name: string): Tool | undefined {
  return autoGeneratedMcpTools.find((tool) => tool.name === name);
}

/** Get all MCP tool names */
export function getMcpToolNames(): string[] {
  return autoGeneratedMcpTools.map((tool) => tool.name);
}
