/**
 * Native Node.js REST API server for markmv
 *
 * Provides a lightweight HTTP API using only Node.js built-in modules. Uses auto-generated route
 * definitions from JSON Schema-first approach. Exposes markmv functionality via RESTful endpoints
 * for language-agnostic access.
 */

import * as http from "node:http";
import * as url from "node:url";
import { createMarkMv } from "./index.js";
import type {
  ApiResponse,
  HealthResponse,
  ErrorResponse,
} from "./types/api.js";
import {
  autoGeneratedApiRoutes,
  getApiRoutePaths,
} from "./schemas/api-routes.js";

const markmv = createMarkMv();
const startTime = Date.now();

const HTTP_OK = 200;
const HTTP_NOT_FOUND = 404;
const HTTP_INTERNAL_SERVER_ERROR = 500;

/** Port used when none is supplied by the caller or the PORT environment variable. */
const DEFAULT_PORT = 3000;

/** Type guard to check if an object is a valid API route */
function isApiRoute(obj: unknown): obj is {
  method: string;
  path: string;
  handler: (
    req: http.IncomingMessage,
    res: http.ServerResponse,
    markmv: ReturnType<typeof createMarkMv>,
  ) => Promise<void>;
} {
  return (
    typeof obj === "object" &&
    obj !== null &&
    "method" in obj &&
    "path" in obj &&
    "handler" in obj &&
    typeof obj.method === "string" &&
    typeof obj.path === "string" &&
    typeof obj.handler === "function"
  );
}

/** Send JSON response with proper headers */
function sendJSON(
  response: http.ServerResponse,
  statusCode: number,
  data: unknown,
): void {
  response.writeHead(statusCode, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
  });
  response.end(JSON.stringify(data));
}

/** Create a standardized API response */
function createApiResponse<T>(
  success: boolean,
  {
    data,
    error,
    details,
  }: Readonly<{
    data?: T;
    error?: string;
    details?: readonly string[];
  }> = {},
): ApiResponse<T> {
  const response: ApiResponse<T> = {
    success,
    timestamp: new Date().toISOString(),
  };

  if (data !== undefined) {
    response.data = data;
  }
  if (error !== undefined) {
    response.error = error;
  }
  if (details !== undefined) {
    response.details = [...details];
  }

  return response;
}

/** Create an error response */
function createErrorResponse(
  statusCode: number,
  error: string,
  message: string,
  details?: readonly string[],
): ErrorResponse {
  const response: ErrorResponse = {
    error,
    message,
    statusCode,
  };

  if (details !== undefined) {
    response.details = [...details];
  }

  return response;
}

/** Handle CORS preflight requests */
function handleCORS(
  request: http.IncomingMessage,
  response: http.ServerResponse,
): boolean {
  if (request.method === "OPTIONS") {
    response.writeHead(HTTP_OK, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, Authorization",
    });
    response.end();

    return true;
  }

  return false;
}

/** Handle health check endpoint */
function handleHealth(response: http.ServerResponse): void {
  const healthResponse: HealthResponse = {
    status: "ok",
    version: "1.0.0",
    uptime: Date.now() - startTime,
    info: {
      service: "markmv-api",
      description: "Markdown file operations API",
    },
  };

  const apiResponse = createApiResponse(true, { data: healthResponse });
  sendJSON(response, HTTP_OK, apiResponse);
}

/** Main request handler */
async function handleRequest(
  request: http.IncomingMessage,
  response: http.ServerResponse,
): Promise<void> {
  // Handle CORS preflight
  if (handleCORS(request, response)) {
    return;
  }

  const { method, url: reqUrl } = request;
  const parsedUrl = url.parse(reqUrl ?? "", true);
  const path = parsedUrl.pathname;

  try {
    // Handle health endpoint
    if (method === "GET" && path === "/health") {
      handleHealth(response);

      return;
    }

    // Handle auto-generated API routes
    const autoRoute = autoGeneratedApiRoutes.find((route: unknown) => {
      return (
        isApiRoute(route) && route.method === method && route.path === path
      );
    });

    if (autoRoute && isApiRoute(autoRoute)) {
      // Call the auto-generated handler with the markmv instance
      await autoRoute.handler(request, response, markmv);

      return;
    }

    // Route not found
    const availableRoutes = [
      "GET /health",
      ...getApiRoutePaths().map((p: string) => `POST ${p}`),
    ];
    const errorResponse = createErrorResponse(
      HTTP_NOT_FOUND,
      "NotFound",
      `Route ${String(method)} ${String(path)} not found`,
      [`Available routes: ${availableRoutes.join(", ")}`],
    );
    sendJSON(response, HTTP_NOT_FOUND, errorResponse);
  } catch (error) {
    console.error("Unhandled error:", error);
    const errorResponse = createErrorResponse(
      HTTP_INTERNAL_SERVER_ERROR,
      "InternalServerError",
      "An unexpected error occurred",
    );
    sendJSON(response, HTTP_INTERNAL_SERVER_ERROR, errorResponse);
  }
}

/** Create and start the HTTP server */
export function createApiServer(port = DEFAULT_PORT): http.Server {
  const server = http.createServer((request, response) => {
    void handleRequest(request, response);
  });

  server.listen(port, () => {
    console.log(`markmv API server running on port ${String(port)}`);
    console.log(`Health check: http://localhost:${String(port)}/health`);
    console.log(`API endpoints: http://localhost:${String(port)}/api/*`);
  });

  return server;
}

/**
 * Starts the API server on the given port, falling back to the PORT environment variable and then
 * to the default port.
 * @param port - The port to listen on, when it should override the environment
 * @returns The listening HTTP server
 */
export function startApiServer(port?: number): http.Server {
  const { PORT } = process.env;
  const fromEnvironment =
    PORT !== undefined && PORT !== "" ? parseInt(PORT, 10) : DEFAULT_PORT;

  return createApiServer(port ?? fromEnvironment);
}
